apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/muruganm0608/flux.git
  ref:
    branch: main

