apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/my-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  targetNamespace: default

